const VALID_TRANSITIONS: Record<string, string[]> = {
  DRAFT: ["CANDIDATES_SELECTED", "CANCELLED"],
  CANDIDATES_SELECTED: ["INVITES_DISPATCHED", "CANCELLED"],
  INVITES_DISPATCHED: ["PREQUAL_IN_PROGRESS", "CANCELLED"],
  PREQUAL_IN_PROGRESS: ["PREQUAL_COMPLETE", "CANCELLED"],
  PREQUAL_COMPLETE: ["AWARDED", "CANCELLED"],
  AWARDED: ["FULL_PACK_SUBMITTED", "CANCELLED"],
  FULL_PACK_SUBMITTED: ["DEEP_VERIFICATION"],
  DEEP_VERIFICATION: ["APPROVALS_IN_PROGRESS"],
  APPROVALS_IN_PROGRESS: ["CONTRACT_REVIEW"],
  CONTRACT_REVIEW: ["ERP_PUSH"],
  ERP_PUSH: ["COMPLETED"],
  COMPLETED: [],
  CANCELLED: [],
};

export function validateTransition(current: string, target: string): boolean {
  return VALID_TRANSITIONS[current]?.includes(target) ?? false;
}
